# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohttpserver < Formula
  desc ""
  homepage ""
  version "1.0.8"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/codeskyblue/gohttpserver/releases/download/1.0.8/gohttpserver_1.0.8_darwin_amd64.tar.gz"
    sha256 "a3b50db155bcbdb8682580db32c424595bd3cbb6c89be06fff1023fb8738cec5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/codeskyblue/gohttpserver/releases/download/1.0.8/gohttpserver_1.0.8_linux_amd64.tar.gz"
    sha256 "3064babe7b58f9e73179415cf8fac811f856be1a82c4484dbd85f59db410687a"
  end

  def install
    bin.install "gohttpserver"
  end
end
