# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohttpserver < Formula
  desc ""
  homepage ""
  version "1.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.4/gohttpserver_1.1.4_darwin_amd64.tar.gz"
      sha256 "2826b00f24cea0cf4713cabcf2167987bc49955f792ec07c9d53a11cd6ad4033"

      def install
        bin.install "gohttpserver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.4/gohttpserver_1.1.4_darwin_arm64.tar.gz"
      sha256 "8e51cc2bde1a59fae3757fac1fc4bcd9a7f7ff886ef2ddec573cfaa75c02cbad"

      def install
        bin.install "gohttpserver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.4/gohttpserver_1.1.4_linux_arm64.tar.gz"
      sha256 "aca46287b1aa0caa1e71569ece86ace39a70715e47e7c7f6d01787cee3d36e04"

      def install
        bin.install "gohttpserver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.4/gohttpserver_1.1.4_linux_amd64.tar.gz"
      sha256 "7ddbbee7268f4d89bd008351a6bf99336615587cc2a900fefb7d924442b95db2"

      def install
        bin.install "gohttpserver"
      end
    end
  end
end
