# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohttpserver < Formula
  desc ""
  homepage ""
  version "1.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.0/gohttpserver_1.1.0_darwin_amd64.tar.gz"
    sha256 "c1b8912982bdd18231cddbf49f052147f5311ed39fba38909d3d533e4eae600d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.0/gohttpserver_1.1.0_darwin_arm64.tar.gz"
    sha256 "97bf19b73b278d279359a095343f4b9a8f67e8b3a690c1561b6dede51edb124b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.0/gohttpserver_1.1.0_linux_amd64.tar.gz"
    sha256 "158332c59bc594e190bf86f8d282bae2cc94498224cc8fd0dc70cf229bf41a55"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/codeskyblue/gohttpserver/releases/download/1.1.0/gohttpserver_1.1.0_linux_arm64.tar.gz"
    sha256 "3aa211fed66ab319297f40c16d6d5bc94192bd82c85e8aad0e7dad6ffcb77ad2"
  end

  def install
    bin.install "gohttpserver"
  end
end
